apiVersion: v1
kind: Pod
metadata:
  name: nodejs-log-pod
spec:
  containers:
    - name: nodejs
      image: pappukrs/nodejs-demo:v2
      volumeMounts:
        - name: log-volume
          mountPath: /app/logs
  volumes:
    - name: log-volume
      hostPath:
        path: /data/nodejs-logs
        type: DirectoryOrCreate
