apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
  namespace: prod
spec:
  type: NodePort
  selector:
    app: nodejs
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 32002
