apiVersion: v1
kind: Pod
metadata:
  name: nodejs-pod
  labels:
    app: nodejs-app
spec:
  containers:
    - name: nodejs-container
      image: pappukrs/nodejs-demo:v1
      ports:
        - containerPort: 3000
      env:
        - name: PORT
          value: "3000"
